version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: leetlink-postgres
    environment:
      POSTGRES_DB: leetlinkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: leetlink-backend
    depends_on:
      - postgres
    ports:
      - "8001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/leetlinkdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  pgdata:
